# midway = Intel OpenMPI FFTW
# hostname = midway.uchicago.edu
#
## module load intel
# module load intelmpi
# # module load fftw3

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler/linker settings
# generally no need to edit this section
# unless additional compiler/linker flags or libraries needed for your machine

CC =		mpicxx
CCFLAGS =	-O2 -DLAMMPS_PLUMED -DMPICH_IGNORE_CXX_SEEK
DEPFLAGS =	-M
LINK =		mpicxx
LINKFLAGS =	-O2 
LIB =           
ARCHIVE =	ar
ARFLAGS =	-rc
SIZE =		size

# ---------------------------------------------------------------------
# LAMMPS-specific settings
# edit as needed for your machine

# LAMMPS ifdef options, see doc/Section_start.html

LMP_INC =	-DLAMMPS_XDR

# MPI library, can be src/STUBS dummy lib
# INC = path for mpi.h, MPI compiler settings
# PATH = path for MPI library
# LIB = name of MPI library

MPI_INC =       #-I/opt/sun-ct/include -DOMPI_SKIP_MPICXX
MPI_PATH =	#-L/opt/sun-ct/lib/lib64
MPI_LIB =	#-lstdc++ -lmpi 

# FFT library, can be -DFFT_NONE if not using PPPM from kspace package
# INC = -DFFT_FFTW, -DFFT_INTEL, -DFFT_NONE, etc, FFT compiler settings
# PATH = path for FFT library
# LIB = name of FFT library

FFTW =/software/fftw3-3.3-el6-x86_64

FFT_INC =       -DFFT_FFTW3 -I${FFTW}/include
FFT_PATH =	-L${FFTW}/lib
FFT_LIB =	-lfftw3

# additional system libraries needed by LAMMPS package libraries
# these settings are IGNORED if the corresponding LAMMPS package
#   (e.g. gpu, meam) is NOT included in the LAMMPS build
# SYSLIB = names of libraries
# SYSPATH = paths of libraries

gpu_SYSLIB =       -lcudart
meam_SYSLIB =      -lgfortran
reax_SYSLIB =      -lgfortran
user-atc_SYSLIB =  -lblas -llapack

gpu_SYSPATH =      -L/usr/local/cuda/lib64
meam_SYSPATH =     -L/usr/local/lib/x86_64
reax_SYSPATH =     -L/usr/local/lib/x86_64
user-atc_SYSPATH = 	

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

include	Makefile.package

EXTRA_INC = $(LMP_INC) $(PKG_INC) $(MPI_INC) $(FFT_INC)
EXTRA_PATH = $(PKG_PATH) $(MPI_PATH) $(FFT_PATH) $(PKG_SYSPATH)
EXTRA_LIB = $(PKG_LIB) $(MPI_LIB) $(FFT_LIB) $(PKG_SYSLIB)

vpath %.cpp ../
vpath %.h ../

# Link target

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) $(OBJ) $(EXTRA_LIB) $(LIB) -o $(EXE)
	$(SIZE) $(EXE)

# Library target

lib:	$(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(EXE) $(OBJ)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
