# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -DLMP_USER_OMP 
PKG_PATH =  
PKG_LIB =     $(PLUMED_LOAD) $(PLUMED_LOAD) 
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  
PKG_SYSLIB =  
PKG_SYSPATH = 
